services:
  db:
    image: postgres:11-alpine
    ports: ["5432:5432"]
    env_file: 
      - .env
    volumes:
    - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports: ["8080:8080"]

volumes:
  db-data: {}
