name: Test event store
on: [push, workflow_dispatch]
defaults:
  run:
    shell: bash
jobs:
  test-event-store:
    runs-on: [ubuntu-latest]
    env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Test event store
      run: npm run test
